### ISSUE TITLE
please add support for darwin-arm64

### ISSUE THREAD

**Issue by fusionbeam** [node-3d/deps-uiohook-raub#1]

**Comment by raub** [comment]
@fusionbeam can you check if this works? - https://github.com/node-3d/deps-uiohook-raub/releases/tag/0.1.0

**Comment by raub** [comment]
also updated and added MacOS ARM here https://github.com/node-3d/iohook-raub/releases/tag/0.1.0, please let me know if it indeed works

**Comment by fusionbeam** [comment]
confirmed. thank you.
